name: Delete path

on: [pull_request]

jobs:
  remove-path:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Remove file from repo
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        path: 'test-file.md'
        destination_repo: 'kafkasl/delete_from_another_repo'
        user_email: 'pol.avms@gmail.com'
        user_name: 'kafkasl'
        commit_message: 'Kindly removing you from other.'